// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug logging
console.log('Supabase Configuration:');
console.log('- URL:', SUPABASE_URL);
console.log('- Key exists:', !!SUPABASE_PUBLISHABLE_KEY);
console.log('- Key format valid:', SUPABASE_PUBLISHABLE_KEY?.startsWith('eyJ'));
console.log('- Environment:', import.meta.env.MODE);
console.log('- Production:', import.meta.env.PROD);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('⚠️ Missing Supabase configuration. Please check your environment variables.');
  console.error('- SUPABASE_URL missing:', !SUPABASE_URL);
  console.error('- SUPABASE_PUBLISHABLE_KEY missing:', !SUPABASE_PUBLISHABLE_KEY);
}

// Check for placeholder key
if (SUPABASE_PUBLISHABLE_KEY === 'YOUR_ACTUAL_ANON_KEY_HERE' || SUPABASE_PUBLISHABLE_KEY?.includes('PLACEHOLDER')) {
  console.error('🔧 Supabase key is still a placeholder. Please update your environment variables.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});